server:
  port: 30230
  #port: 8082
spring:
 # messages:
  #  basename: i18n/Messages,i18n/Pages
  jms:
    pub-sub-domain: false   # 配置消息的类型，如果是true则表示为topic消息，如果为false表示Queue消息
  activemq:
    user: admin    # 连接用户名
    password: admin   # 连接密码
    broker-url: tcp://127.0.0.1:61616 # 消息组件的连接主机信息
    packages:
      trust-all: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    timeout: 1000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  session:
    store-type: redis
    timeout: 2000

  datasource:
    url: jdbc:mysql://localhost:3306/broker?useSSL=false&serverTimezone=GMT
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: info


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.broker.entity
  mapperLocations: classpath:mapper/*.xml



#spring:
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    producer:
#      retries: 0
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#    consumer:
#      group-id: test-consumer-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer